// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddReviewController from "./add_review_controller"
application.register("add-review", AddReviewController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BookingPickerController from "./booking_picker_controller"
application.register("booking-picker", BookingPickerController)

import DatepickerController from "./datepicker_controller"
application.register("datepicker", DatepickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import ListingEditorController from "./listing_editor_controller"
application.register("listing-editor", ListingEditorController)

import MapController from "./map_controller"
application.register("map", MapController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
